boards:
  - name: skean_left
    vendor: krikun98
    socs:
      - name: nrf52833
        variants:
          - name: zmk
  - name: skean_right
    vendor: krikun98
    socs:
      - name: nrf52833
        variants:
          - name: zmk
